server.port=8080

# Error handling
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Actuator
management.endpoints.web.base-path=/v1/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App info
info.app.name=legacy-api
info.app.description=Legacy API service exposing AWS region information
info.app.version=0.0.1-SNAPSHOT
